### ISSUE TITLE
python 3 absent, can it use v2?

### ISSUE THREAD

**Issue by jhoogeboom** [T-800/REPL-Nodejs#1]
Doing an online course in python on edX which uses python 2, but would like to REPL from atom. However it insists on 3 it seems, is this configurable?

```
ReplManager.coffee:25 ici
ReplManager.coffee:31 ici
events.js:94 Uncaught Error: spawn python3 ENOENT
```

**Comment by etouss** [comment]
So sorry about that we were not able to make a proper config file due to our lake of skill on coffescript and Atom
But you can change it manually 
Juste change the file " ~/.atom/packages/repl/replPython.js"
modify the cmd = "python3" with your path to python or only python 

Thanks for your feedback. and sorry about that.

**Comment by jhoogeboom** [comment]
Works like a charm, thanks!
